language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - TEST_SUITE=unit CI=true
  - TEST_SUITE=acceptance CI=true
  - TEST_SUITE=quality CI=true
notifications:
  irc:
    channels:
      - "irc.freenode.org#berkshelf"
    skip_join: true
    use_notice: true
bundler_args: --without guard
before_script:
  - git config --global user.email "ci@berkshelf.com"
  - git config --global user.name "Berkshelf"
script: 'bundle exec thor spec:$TEST_SUITE'
